#!/usr/bin/env node
/*
 * Copies the shared rendering engine (../js) into the app as strings, so the
 * phone uses exactly the same virtual clock and MP4 encoder as the desktop
 * app and the Premiere/After Effects plugin. Run after changing ../js:
 *   npm run sync-runtime
 */
'use strict';
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..', '..');
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');
const files = {
  INJECT_JS: 'js/core/inject.js',
  MP4_MUXER_JS: 'js/vendor/mp4-muxer.js',
  ENCODER_PAGE_JS: 'js/core/encoder-page.js'
};
let out = '// Generated by scripts/sync-runtime.js from ../js. Do not edit.\n';
for (const [name, file] of Object.entries(files)) {
  out += `\n// ${file}\nexport const ${name}: string = ${JSON.stringify(read(file))};\n`;
}
fs.writeFileSync(path.join(__dirname, '..', 'src', 'runtime', 'generated.ts'), out);
console.log('Wrote src/runtime/generated.ts');
